# Simple workflow for deploying static content to GitHub Pages
name: Update omnivore

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  schedule:
    - cron: "30 */12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update_omnivore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: Gr1N/setup-poetry@v9
      - run: poetry install --no-root
      - run: POCKET_TOKEN=${{secrets.POCKET_TOKEN}} POCKET_CONSUMER_KEY=${{secrets.POCKET_CONSUMER_KEY}} OMNIVORE_API_KEY=${{secrets.OMNIVORE_API_KEY}} poetry run python main.py
